# Generated by Django 5.0.2 on 2024-02-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.PositiveIntegerField(choices=[(3, 'Shop admin'), (2, 'Category admin'), (1, 'Product admin')], default=1),
        ),
    ]
