# Generated by Django 5.0.2 on 2024-02-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazam_express', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='imageUrl',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
