# Generated by Django 5.0.2 on 2024-02-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazam_express', '0002_alter_shop_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_photo',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='images/'),
        ),
    ]
